name    'desalvo-sendmail'
version '0.1.0'
source 'https://github.com/desalvo/puppet-sendmail'
author 'desalvo'
license 'Apache License, Version 2.0'
summary 'Puppet module for sendmail'
description 'Puppet module for sendmail configuration'
project_page 'https://github.com/desalvo/puppet-sendmail'
